<?

class THEAD extends TWEBCONTROL
{

    private $fCssFiles = Array();
    private $fScripts = Array();
    private $fContentBlocks = Array();
    private $fMetaTags = Array();

    public function THEAD()
    {
        parent::TWEBCONTROL();
    }

    public function addCssFile($uri, $id = NULL)
    {
        if ($id)
        {
            $this->fCssFiles[$id] = $uri;
        }
        else
        {
            $this->fCssFiles[] = $uri;
        }
    }

    public function addJavascriptUri($uri, $id = NULL)
    {
        if ($id)
        {
            $this->fScripts[$id] = $uri;
        }
        else
        {
            $this->fScripts[] = $uri;
        }
    }

    public function addContent($content)
    {
        $this->fContentBlocks[] = $content;
    }

    public function setMetaTag($httpEquiv, $name, $content)
    {
        $this->fMetaTags[] = Array("httpEquiv" => $httpEquiv, "name" => $name, "content" => $content);
    }

    protected function toHtml()
    {
        $page = TPAGE::getInstance();
        $charset = $this->getProperty("Charset", TLOCATE::get("SYS_PAGE_CHARSET", "utf-8"));
        $contentType = $this->getProperty("Content-Type", "text/html");

        @Header('Content-type: ' . $contentType . ';charset=' . $charset);

        $html = "";
        $html .= "<!-- HEAD GENERATED BY THE FRAMEWORK -->\n";
        $html .= "<meta http-equiv=\"Content-Type\" content=\"" . $contentType . ";charset=" . $charset . "\" />\n";

        if ($this->hasProperty("Title"))
        {
            $html .= "<title>" . $this->getProperty("Title") . "</title>\n";
        }

        if ($this->hasProperty("Description"))
        {
            $this->addMeta("description", $this->getProperty("Description"));
        }

        if ($this->hasProperty("Keywords"))
        {
            $this->addMeta("keywords", $this->getProperty("Keywords"));
        }

        while (list($tagName, $metaTags) = each($this->fMetaTags))
        {
            $h = isset($metaTags["httpEquiv"]) && $metaTags["httpEquiv"] !== NULL ? " http-equiv='" . $metaTags["httpEquiv"] . "'" : "";
            $n = isset($metaTags["name"]) && $metaTags["name"] !== NULL ? " name='" . $metaTags["name"] . "'" : "";
            $c = isset($metaTags["content"]) && $metaTags["content"] !== NULL ? " content='" . safequot($metaTags["content"]) . "'" : "";
            $html .= "<meta" . $h . $n . $c . ">\n";
        }

        if ($page->hasLookAndFeel())
        {
            $html .= tagLink($page->getLookAndFeel(), Array("id" => "idLafCssLink")) . "\n";
        }
        else
        {
            $html .= tagLink($this->getProperty("SystemCssFile", "/system/assets/css/qphp.css")) . "\n";
        }

        $css_array = $this->fCssFiles;
        $tmp = $this->getProperty("Css");

        if ($tmp && is_array($tmp) && count($tmp) > 0)
        {
            $css_array = array_merge($tmp, $css_array);
        }

        $tmpUsed = Array();

        while (list($id, $css_file) = each($css_array))
        {
            if (!isset($tmpUsed[$css_file]))
            {
                if (is_int($id))
                {
                    $html .= tagLink($css_file) . "\n";
                }
                else
                {
                    $html .= tagLink($css_file, Array('id' => $id)) . "\n";
                }
                $tmpUsed[$css_file] = TRUE;
            }
        }

        $html .= tagScript("/system/scripts/qphp.js.php") . "\n";
        $script_array = $this->fScripts;
        $tmp = $this->getProperty("Scripts");

        if ($tmp && is_array($tmp) && count($tmp) > 0)
        {
            $script_array = array_merge($tmp, $script_array);
        }

        $tmpUsed = Array();

        while (list(, $script_file) = each($script_array))
        {
            if (!isset($tmpUsed[$script_file]))
            {
                $html .= tagScript($script_file) . "\n";
                $tmpUsed[$script_file] = TRUE;
            }
        }


        $html .= "<script type=\"text/javascript\">\n//<![CDATA[\n";
        $html .= "\tvar page;\n";
        $page->agent->OnLoad->systemExecute("page = new TPage()");
        $page->agent->OnLoad->systemExecute("page.submitUri = \"" . $page->request->getPhpSelf() . "\"");

        if (TAPPLICATION::getInstance()->isDevMode())
        {
            $page->agent->OnLoad->systemExecute("page.devMode = true");
        }

        if (isTrue($this->getProperty("AjaxDisabled")))
        {
            
        }
        else
        {
            $page->agent->OnLoad->systemExecute("page.ajax = new THttpAjax()");
        }

        $propertyList = $page->model->getDataModelPropertyList();

        while (list($key, $obj) = each($propertyList))
        {
            if (isset($obj["ba"]) && $obj["ba"] === TRUE && isset($obj["val"]))
            {
                $page->agent->OnLoad->systemExecute("page.model.setProperty(\"" . addslashes($key) . "\", " . json_encode($obj["val"]) . ", " . (isset($obj["sf"]) && $obj["sf"] === TRUE ? "true" : "false") . ")");
            }
        }

        if ($page->hasMessages())
        {
            $page->agent->OnLoad->systemExecute("page.showMessages(" . json_encode($page->getMessages()) . ")");
        }

        if ($page->hasErrors())
        {
            $page->agent->OnLoad->systemExecute("page.showErrors(" . json_encode($page->getErrors()) . ")");
        }

        $page->agent->OnLoad->systemExecute("if (typeof window.finalizePage == 'function') eval('finalizePage()')");
        $page->agent->OnLoad->systemExecute("if (typeof window.OnPageLoad == 'function') eval('OnPageLoad()')");
        $page->agent->OnLoad->systemExecute("page.setFinalized()");

        $codeString = "";
        $codeLines = $page->agent->OnLoad->getSystemExecutableCode();

        while (list($objName, $code) = each($codeLines))
        {
            $codeString .= "\t\t" . $code . ";\n";
        }

        if ($codeString != "")
        {
            $html .= "\tfunction initializePage() {\n" . $codeString . "\t}\n";
            $html .= "\tif (window.attachEvent) {window.attachEvent('onload', function() {initializePage();})} else {window.addEventListener('load', function() {initializePage();}, false)};";
        }

        $codeString = "";
        $codeLines = $page->agent->OnUnload->getExecutableCode();

        while (list($objName, $code) = each($codeLines))
        {
            $codeString .= "\t\t" . $code . ";\n";
        }

        if ($codeString != "")
        {
            $html .= "\tif (window.attachEvent) {window.attachEvent('onunload', function() {\n" . $codeString . "\t})} else {window.addEventListener('unload', function() {\n" . $codeString . "\t};";
        }

        $html .= "\n//]]>\n</script>\n";

        while (list(, $block) = each($this->fContentBlocks))
        {
            $html .= $block . "\n";
        }

        $html .= "<!-- // HEAD GENERATED BY THE FRAMEWORK -->\n";
        return $html;
    }

}

?>